### ISSUE TITLE
FormsPlot null reference exception in .NET Core 3.0

### ISSUE THREAD

**Issue by petarpetrovt** [swharden/ScottPlot#138]
Creating new `FormsPlot` throws null reference exception.

Version:
NuGet package: 3.1.4

SDK:
dotnet core 3.0.100

Code:
`this.FormsPlot = new ScottPlot.FormsPlot();`

CallStack:
   at ScottPlot.FormsPlot.Render(Boolean skipIfCurrentlyRendering, Boolean lowQuality)
   at ScottPlot.FormsPlot.PbPlot_SizeChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl, Boolean updateWindowFontIfNeeded)
   at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds)
   at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at ScottPlot.FormsPlot.InitializeComponent()
   at ScottPlot.FormsPlot..ctor()
   at WindowsFormsApp1.Form1.InitializeComponent() in C:\Projects\sharpa\test\WindowsFormsApp1\Form1.Designer.cs:line 33
   at WindowsFormsApp1.Form1..ctor() in C:\Projects\sharpa\test\WindowsFormsApp1\Form1.cs:line 17
   at WindowsFormsApp1.Program.Main() in C:\Projects\sharpa\test\WindowsFormsApp1\Program.cs:line 20

**Comment by swharden** [comment]
Hi @petarpetrovt, thank you for providing these details! I think this issue has been fixed as part of #131 within the last week, but not yet published on NuGet. 

Would you be up to downloading the latest source from GitHub and referencing ScottPlot that way? I'd be interested to know if this fixes your problem!

**Comment by petarpetrovt** [comment]
Hi @swharden, i build the source and replaced in my project.  The same error continues.

ScotPlot.dll -> 3.1.5 version

**Comment by swharden** [comment]
Hi @petarpetrovt thanks for looking into it!

I can replicate this error on my system, but the error only affects .NET Core (not .NET Framework) applications. The missing object is `lastInteractionTimer`, and @StendProg might be able to provide more some insight here.

I just added a null check to the master branch (350f5cf7b06db378b38635ae4ebcc9123cfe444e) which fixes this issue on my system. Does this fix your problem as well?

**Comment by petarpetrovt** [comment]
Hi @swharden the null check seems to have fixed the problem.

**Comment by swharden** [comment]
> Hi @swharden the null check seems to have fixed the problem.

This is great news! I'll include this fix with the next NuGet release. Thanks again for raising this issue

**Comment by swharden** [comment]
This issue arose again (as pointed out by @petarpetrovt in #189) after the WinForms control was re-written from scratch (probably affecting all versions from 4.0.0 - 4.0.6).

The cause of this issue is that `FormsPlot.plt` is null when a `SizeChanged` event is triggered. This is highly unexpected because the constructor of `FormsPlot` initializes `FormsPlot.plt`. I do not understand how .NET Core 3.0 WinForms control events can be called before the controls themselves are initialized, but adding a null check fixed the issue (again).

To ensure the WinForms control continues to work in .NET Core 3.0, a WinFormsCore Quickstart project was added to the demos folder.

![image](https://user-images.githubusercontent.com/4165489/69917931-b0324f80-1439-11ea-8e34-2fc7f32da836.png)
