### ISSUE TITLE
user control thread safety

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#165]
I get some exceptions using ScottPlot formsPlot user control. I use the latest ScottPlot version, under VS2019 in a WinForm project. I have another project, where the exception generated always when minimizing the main Form window, however I cannot paste that project as it is, but I will try to reduce/remove company info tomorrow and post that one as well.

I attach the test project which only generates the exception randomly. Reproducing the problem: run the Release EXE, and start to resize the Form window dragging by its right border, to the minimum size (when practically the plot is not visible), then back. Repeat this many times, and sometimes you get exceptions, like the two pasted below.

[scottplottest1.zip](https://github.com/swharden/ScottPlot/files/3805046/scottplottest1.zip)

> System.InvalidOperationException: Object is currently in use elsewhere.
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font)
   at ScottPlot.TickCollection.UpdateLongestLabel(Settings settings, Boolean verticalAxis)
   at ScottPlot.TickCollection.Recalculate(Settings settings, Boolean verticalAxis)
   at ScottPlot.Renderer.FigureTicks(Settings settings)
   at ScottPlot.Plot.RenderBitmap()
   at ScottPlot.Plot.GetBitmap(Boolean renderFirst, Boolean lowQuality)
   at ScottPlot.FormsPlot.Render(Boolean skipIfCurrentlyRendering, Boolean lowQuality)
   at ScottPlot.FormsPlot.PbPlot_SizeChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

> System.NullReferenceException: Object reference not set to an instance of an object.
   at ScottPlot.Renderer.RenderTicksOnLeft(Settings settings)
   at ScottPlot.Renderer.FigureTicks(Settings settings)
   at ScottPlot.Plot.RenderBitmap()
   at ScottPlot.Plot.GetBitmap(Boolean renderFirst, Boolean lowQuality)
   at ScottPlot.FormsPlot.Render(Boolean skipIfCurrentlyRendering, Boolean lowQuality)
   at ScottPlot.FormsPlot.PbPlot_SizeChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by swharden** [comment]
@bukkideme I'm pretty sure this error is caused by any program which attempts to make System.Drawing calls (using GDI+) in a parallel-processing environment. I don't think GDI+ calls are thread-safe.

```cs
aTimer = new System.Timers.Timer(500);
```

I would guess if you make the timer `100`, crashes will happen 5 times more often 😈 

This is good to know, as it means programs which involve plotting live data are susceptible to crashes if updates occur while the user control is resizing!

Would an acceptable solution be to wrap your `OnTimedEvent` code in a try/catch?

**Comment by swharden** [comment]
I actually fixed this bug in your application by using a `System.Windows.Forms.Timer` (drag/dropping it from the toolbox onto your Form) rather than a `System.Timers.Timer`

I'm guessing the Forms timer has better support support for GDI+

**Comment by bukkideme** [comment]
Actually the other application which crashed at each and all resize attempt, uses the old school Backgroundworker class. I wonder how it makes it different. Actually this app was a reworked old one, in my newer apps i use TAP approach which is the recommended parallel solution. Hmm, would it make any difference using a Task...?

Anyway, since this is a window resize event, there are many options to avoid such crashes, including your suggestion.
Thanks for feedback!

**Comment by swharden** [comment]
> Anyway, since this is a window resize event, there are many options to avoid such crashes, including your suggestion.

Keep in mind your program also crashes if `System.Timers.Timer` triggers an update while actively click-dragging to pan or zoom (not just resize events). Using `System.Windows.Forms.Timer` protects against this too.
