### ISSUE TITLE
GDI error when saving large PNG files

### ISSUE THREAD

**Issue by jmecosta** [swharden/ScottPlot#288]
hi,

didnt find any reference to this

```
[00:30:28]F:				 [FTC_3567.Performance_ImportShape_20_1_ENU_DEFAULT.MacroExec] FTC_3567.FatalException
[00:30:28] :					 [FTC_3567.FatalException]   10/03/2020 0.30.28 : RecordFailure: FTC_3567.FatalException => Testware Failure: A generic error occurred in GDI+. => sStackTrakce: =>    at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
[00:30:28] :					 [FTC_3567.FatalException]      at System.Drawing.Image.Save(String filename, ImageFormat format)
[00:30:28] :					 [FTC_3567.FatalException]      at ScottPlot.Plot.SaveFig(String filePath, Boolean renderFirst)
[00:30:28] :					 [FTC_3567.FatalException]      at TafSdk.Performance.PerfMonitor.AnalyseAndPlotData(KeyValuePair`2 currentRunMeasures, IMessageLogger logger, String perfModelFolder, String refModelFolder, String runPerFileName, TestManager testManager) in E:/prod/ts-build/Test/TestTools/TestAdapters/TafSdk/Performance/PerfMonitor.cs:line 355
[00:30:28] :					 [FTC_3567.FatalException]      at TafSdk.Performance.PerfMonitor.ProcessDataAndSave(String ftcCaseName, String caseId, String modelPath, String refModelFolder, IMessageLogger logger, TestManager testManager) in E:/prod/ts-build/Test/TestTools/TestAdapters/TafSdk/Performance/PerfMonitor.cs:line 132
[00:30:28] :					 [FTC_3567.FatalException]      at FarmiAdapterUtils.FarmiModelHelpers.<RunMacrosAgainstModel>d__64.MoveNext() in E:/prod/ts-build/Test/TestTools/TestAdapters/FarmiAdapterUtils/FarmiModelHelpers.cs:line 3212
[00:30:28] :					 [FTC_3567.FatalException]   --- End of stack trace from previous location where exception was thrown ---
[00:30:28] :					 [FTC_3567.FatalException]      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:30:28] :					 [FTC_3567.FatalException]      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:30:28] :					 [FTC_3567.FatalException]      at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[00:30:28] :					 [FTC_3567.FatalException]      at FarmiAdapterUtils.FarmiModelHelpers.<RunTafTestCase>d__17.MoveNext() in E:/prod/ts-build/Test/TestTools/TestAdapters/FarmiAdapterUtils/FarmiModelHelpers.cs:line 956
[00:30:28] :					 [FTC_3567.FatalException]   --- End of stack trace from previous location where exception was thrown ---
[00:30:28] :					 [FTC_3567.FatalException]      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:30:28] :					 [FTC_3567.FatalException]      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:30:28] :					 [FTC_3567.FatalException]      at FarmiAdapterUtils.FarmiModelHelpers.<RunCases>d__14.MoveNext() in E:/prod/ts-build/Test/TestTools/TestAdapters/FarmiAdapterUtils/FarmiModelHelpers.cs:line 510
[00:30:28] :					 [FTC_3567.FatalException]   10/03/2020 0.30.28 : teamcity[testFailed name='FTC_3567.FatalException' message='The following error messages were found :|nStackTrakce: =>    at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)|r|n   at System.Drawing.Image.Save(String filename, ImageFormat format)|r|n   at ScottPlot.Plot.SaveFig(String filePath, Boolean renderFirst)|r|n   at TafSdk.Performance.PerfMonitor.AnalyseAndPlotData(KeyValuePair`2 currentRunMeasures, IMessageLogger logger, String perfModelFolder, String refModelFolder, String runPerFileName, TestManager testManager) in E:/prod/ts-build/Test/TestTools/TestAdapters/TafSdk/Performance/PerfMonitor.cs:line 355|r|n   at TafSdk.Performance.PerfMonitor.ProcessDataAndSave(String ftcCaseName, String caseId, String modelPath, String refModelFolder, IMessageLogger logger, TestManager testManager) in E:/prod/ts-build/Test/TestTools/TestAdapters/TafSdk/Performance/PerfMonitor.cs:line 132|r|n   at FarmiAdapterUtils.FarmiModelHelpers.<RunMacrosAgainstModel>d__64.MoveNext() in E:/prod/ts-build/Test/TestTools/TestAdapters/FarmiAdapterUtils/FarmiModelHelpers.cs:line 3212|r|n--- End of stack trace from previous location where exception was thrown ---|r|n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)|r|n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)|r|n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)|r|n   at FarmiAdapterUtils.FarmiModelHelpers.<RunTafTestCase>d__17.MoveNext() in E:/prod/ts-build/Test/TestTools/TestAdapters/FarmiAdapterUtils/FarmiModelHelpers.cs:line 956|r|n--- End of stack trace from previous location where exception was thrown ---|r|n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)|r|n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)|r|n   at FarmiAdapterUtils.FarmiModelHelpers.<RunCases>d__14.MoveNext() in E:/prod/ts-build/Test/TestTools/TestAdapters/FarmiAdapterUtils/FarmiModelHelpers.cs:line 510' details='Testware Failure: A generic error occurred in GDI+.']
[00:30:28] :					 [FTC_3567.FatalException]   10/03/2020 0.30.28 : 
```

Can it be the size of the png being 2 big?

```cs
var plt = new ScottPlot.Plot(2000, 1000);
```

**Comment by swharden** [comment]
@jmecosta thanks for sharing this error message!

I'm not aware what the maximum file size is for `System.Drawing` but 2000x1000 doesn't seem very large. Can you share the code you are using to call plt.SaveFig? It seems more likely that the error might be there...

**Comment by jmecosta** [comment]
sure:
![image](https://user-images.githubusercontent.com/1041352/76331290-99807c00-62f7-11ea-8ff6-36d50894320c.png)

this works most of the times! maybe its related with the data itself?

**Comment by swharden** [comment]
Perhaps you can gain insight by separating the rendering (ScottPlot) from the PNG encoding and file saving (GDI) tasks:

```cs
// use ScottPlot to render the plot as a Bitmap
System.Drawing.Bitmap bmp = plt2.GetBitmap();

// Save the Bitmap using the PNG encoder
string imageFilePath = "some/crazy/path.png";
bmp.Save(imageFilePath, System.Drawing.Imaging.ImageFormat.Png);
```

Using code like this, where does the failure occur?

**Comment by jmecosta** [comment]
it occurrs in a some tests! doesnt seem to be related with agent since others tests run fine in that agent! i would say its most likely the data set that is causing the issue. i will do what u suggested and let u know if it works. thanks

**Comment by swharden** [comment]
> I would say its most likely the data set that is causing the issue.

Sounds good! I'll close this issue for now, but if you find that ScottPlot is the underlying cause feel free to open the issue again (perhaps with sample data that causes crashes) and I can take a closer look.

I'm glad you enjoy using ScottPlot! Good luck with your coding 👍
