### ISSUE TITLE
Cannot create an instance of "WpfPlot"

### ISSUE THREAD

**Issue by Helitune-RobMcKay** [swharden/ScottPlot#466]
**Describe the bug**
When using the WpfPlot object, it fails to load in the design view. It fails with the following error:

Cannot create an instance of "WpfPlot" is shown in the design view

The error details are:
```
FileNotFoundException: Could not load file or assembly 'ScottPlot.WPF, Version=4.0.34, Culture=neutral' or one of its dependencies. The system cannot find the file specified.

 at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)
   at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String& partName, Boolean& isContentFile)
   at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)
   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
   at System.IO.Packaging.Package.GetPart(Uri partUri)
   at System.Windows.Application.GetResourceOrContentPart(Uri uri)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ScottPlot.WpfPlot.InitializeComponent()
   at ScottPlot.WpfPlot..ctor()
```

**To Reproduce**
1. Create a new WPF project in VS2019 targeting either .Net 4.6.1 or 4.6.2
2. add ScottPlot nuget package to the project
3. add the WpfPlot object 

**Screenshots**
If applicable, add screenshots to help explain your problem

![image](https://user-images.githubusercontent.com/16836671/84754373-35391c80-afb8-11ea-80c0-02f916ad6dcb.png)

**Comment by swharden** [comment]
Hey @Helitune-RobMcKay, someone recently posted a similar report in #356 that only affects WpfPlot on .NET Framework

The solution there was to ensure the project uses the SDK-style csproj format.

One way to test this is to create a .NET Core WPF project, then edit the csproj file to make it target .NET Framework

Let me know if this works for you!

**Comment by Helitune-RobMcKay** [comment]
It worked. 

Thank you @swharden .
