### ISSUE TITLE
XamlParseException upon installing the package

### ISSUE THREAD

**Issue by TetheredSun** [swharden/ScottPlot#487]
Immediately after installing the ScottPlot and ScottPlot.WPF packages, my fresh solution throws a XamlParseException. This is before I add a single line of code. The exception stack trace is as follows (with the Hungarian messages translated back to English):

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=The method or operation is not implemented.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at ScottPlot.App.Main()
```

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NotImplementedException: The method or operation is not implemented.

**Comment by swharden** [comment]
Hi @TetheredSun, thank you for reporting this!

Unfortunately I cannot recreate this error. When I create a new .NET Core WPF application and install ScottPlot.WPF with NuGet, it installs without error and even appears in my toolbox.

My success is in a **.NET Core 3.1** application using **Visual Studio Community 2019 16.6.3** (the latest current version). What platform and version of Visual Studio are you using to produce this error?

**Comment by swharden** [comment]
These pages seem to describe a similar issue. 

Does creating a new project from scratch _in a different file path_ fix your issue?

* https://docs.telerik.com/reporting/knowledge-base/error-building-project-after-adding-wpf-report-viewer
* https://stackoverflow.com/questions/51933251/xamlparseexception-provide-value-on-system-windows-markup-staticresourcehold
* https://stackoverflow.com/questions/44048947/system-windows-markup-xamlparseexception-occurred-microsoft-visual-studio-commu

**Comment by TetheredSun** [comment]
Thank you very much for your fast reply, Scott!

That was the problem. I did not create a .NET Core application but a classic .NET Framework application (I did use the current Visual Studio).  With a .NET Core application, it works fine.

My deepest apologies for the false alarm and thank you again for your help.

**Comment by swharden** [comment]
Hey @TetheredSun, I'm happy you solved the issue! I'm somewhat surprised you had that problem, as on my end ScottPlot for WPF works in .NET Framework 4.6.2 and above, but either way I'm glad you got it figured out.

I hope you enjoy using ScottPlot!
